### ISSUE TITLE
[Not a bug] Thank you

### ISSUE THREAD

**Issue by ianozsvald** [ZaxR/bulwark#11]
This is a quick note to say Thank You. When I teach good data science practice I now include bulwark (in place of engarde) and in my own code I've switched to bulwark.

Your tool is necessary, I hope to see a nice set of standard checks being added by other data scientists. Thanks for your time, Ian.

**Comment by ZaxR** [comment]
Thanks for the comment, Ian! It's great to get feedback. If there's any features you'd like to see, please feel free to create an issue :)
