### ISSUE TITLE
Possible new check: generalized has_no_x

### ISSUE THREAD

**Issue by ZaxR** [ZaxR/bulwark#12]
`df[<given_cols>].isin(<given_vals>).any()`

**Comment by ZaxR** [comment]
Have has_no_nan, inf, neg_inf call generalized func

**Comment by ehenry09** [comment]
@ZaxR -- I'll take this one. Gotta sink my teeth into the code a bit more tho :)

**Comment by ZaxR** [comment]
Awesome! Let me know if I can help you understand anything. If you haven't done PRs under the forking workflow before, here are github's instructions: https://help.github.com/en/articles/working-with-forks

**Comment by ZaxR** [comment]
Closed by PR #28
