### ISSUE TITLE
Possible new check: has_n_values

### ISSUE THREAD

**Issue by ZaxR** [ZaxR/bulwark#14]
```
def has_n_values(df, items):
        """Has exactly n unique values in specified columns."""
        cols_n_unique = dict(df[list(items.keys())].nunique())
        bad_cols = [col for col, n_unique in items.items() if cols_n_unique[col] != n_unique]

        if bad_cols:
            raise AssertionError(f"The following columns have a different number of unique items than expected: "
                                 f"{', '.join(bad_cols)}")
```

**Comment by ZaxR** [comment]
Perhaps have a convenience wrapper to check for uniqueness

**Comment by ZaxR** [comment]
Want to give the option of including np.nan, None, and/or falsy values as part of nunique.

E.g.

remove_falsy=True, remove_nan=True
vals = [v for v in vals if not ((remove_falsy and not v) or (remove_nan and pd.isnull(v)))]

**Comment by ZaxR** [comment]
Might be too trivial to have as a check?

**Comment by dataviolinist** [comment]
Use case for this particular check where a certain column should have specific count of unique values may not have broad scope of application and can be addressed on a case by case basis as needed.

**Comment by ZaxR** [comment]
Agreed - thanks for thinking through this. Going to close this issue.
