### ISSUE TITLE
Deprecate old func names

### ISSUE THREAD

**Issue by ZaxR** [ZaxR/bulwark#34]
The following function name changes should occur, with deprecation for old names:

within_set -> has_vals_within_set
within_range -> has_vals_within_range
within_n_std -> has_vals_within_n_std

Warning messages should be generated with the warnings module:

```
import warnings

# Required for DeprecationWarnings to not be ignored
warnings.simplefilter('always', DeprecationWarning)

warnings.warn("This function has been renamed to xxx. The old name will be removed in x.x"
                         "Switch to the from_hierarchy_id method for identical functionality.",
                         DeprecationWarning,
                         stacklevel=1)
```

**Comment by abatula** [comment]
I'll work on this one

**Comment by ZaxR** [comment]
In addition to those above, it'd be nice to have deprecation warnings for functions that were renamed from those found in engarde, to help folks migrate:

none_missing became has_no_nans
unique_index became has_unique_index
