### ISSUE TITLE
Could we have a conda recipe please?

### ISSUE THREAD

**Issue by ianozsvald** [ZaxR/bulwark#45]
I believe at present we don't have a conda-forge recipe for bulwark to enable a `conda install`. I teach `bulwark` in my public classes (Software Engineering for Data Scientists) and promote it during public talks, it is the only install in that set that has to fall back on pip which breaks the conda dependency management.

Is there any chance you'd add a conda recipe please?

**Comment by ZaxR** [comment]
Thanks - this wasn't on my radar. I haven't created a conda recipe before, but I'll take a look into getting this added.

Notes for me:
- https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html
- `conda skeleton pypi --pypi-url <mirror-url> package_name`

**Comment by ianozsvald** [comment]
It has been years since I last built a recipe - the bugbear I had last time was that cached results confused the development process. I wrote up some notes, they _may_ no longer be valid but the notes on caching and how to clear it may still have value: https://ianozsvald.com/2016/08/19/some-notes-on-building-a-conda-recipe/

Thank you for considering this :-) It will definitely expand the scope of your installed users.

**Comment by jamesmyatt** [comment]
You can probably just take and modify the engarde feedstock: https://github.com/conda-forge/engarde-feedstock

**Comment by jamesmyatt** [comment]
FYI: https://github.com/conda-forge/staged-recipes/pull/9936

**Comment by jamesmyatt** [comment]
Feedstock is now here: https://github.com/conda-forge/bulwark-feedstock

**Comment by ianozsvald** [comment]
That's brilliant - cheers! I'll use this in future classes for sure!
