### ISSUE TITLE
Chg to simpler workflow than Gitflow

### ISSUE THREAD

**Issue by jamesmyatt** [ZaxR/bulwark#50]
It looks like you're planning to follow a strict gitflow (https://nvie.com/posts/a-successful-git-branching-model/).

To start with, I don't recommend that you do; the overheads are unjustified for a small open-source project. I'm not aware (but that's probably just me) of any open-source projects following it successfully.

However, if you do then, then:

1. You need to merge release branches back into develop and not just master
1. I recommend making sure that this is prominently stated in the [Readme](README.md) and upfront in the contributing guide. Also link to the contributing guide from the Readme.
1. I recommend setting the default branch to develop (#51).
1. It might be worth protecting the master branch (https://help.github.com/en/articles/defining-the-mergeability-of-pull-requests)

**Comment by ZaxR** [comment]
Yup - thanks - just forgot the merge back to develop (I'm using gitflow manually). 

I have CD on the master branch that includes deployment to PyPI, so I don't want merges directly into master. The result would be a failed PyPI push (if there's no version change) and then a failed build status. 

I had thought the contributing page made the workflow clear, but open to adjusting it to make it clearer: https://bulwark.readthedocs.io/en/latest/contributing.html

Definitely open to a different workflow - do you have any suggestions?

**Comment by jamesmyatt** [comment]
I think that you need an outline of the contributing guide and a link in the Readme.

I think that you can trigger the CD on tags, rather than just commits to master (https://docs.travis-ci.com/user/deployment/releases/#deploying-only-on-tagged-builds) so you don't need to maintain two main branches.

**Comment by ZaxR** [comment]
Good call with the CD on tags - was just reading about that independently. That should simply things a lot. I'm definitely all about making it easier to contribute. After the six PR, I'll work on the CD change and making the updates to the docs. I plan to borrow from this as well: https://scikit-learn.org/stable/developers/contributing.html#pull-request-checklist

**Comment by jamesmyatt** [comment]
This contains great guidance on making projects maintainable: https://hynek.me/talks/python-foss/

**Comment by ZaxR** [comment]
The name of the workflow we're talking about: https://trunkbaseddevelopment.com/

**Comment by ZaxR** [comment]
> This contains great guidance on making projects maintainable: https://hynek.me/talks/python-foss/

This is actually open in a tab in my browser already - been on my to-watch list for weeks lol

**Comment by jamesmyatt** [comment]
> The name of the workflow we're talking about: https://trunkbaseddevelopment.com/

I think so. I wasn't aware that there was an accepted name for it. But I think that feature branches are valuable for open-source (https://trunkbaseddevelopment.com/short-lived-feature-branches/).

**Comment by jamesmyatt** [comment]
> > This contains great guidance on making projects maintainable: https://hynek.me/talks/python-foss/
> 
> This is actually open in a tab in my browser already - been on my to-watch list for weeks lol

*Do it now* ;-)

**Comment by ZaxR** [comment]
@jamesmyatt - If you have some time this weekend, would you be willing to look at the feature branch referenced above? I did my best to make the master/tags change as well as a number of CI/CD improvements per the pycon talk and a few others. Definitely open to any changes as well.
