### ISSUE TITLE
Ability to specify additional locations of DataFrame to check

### ISSUE THREAD

**Issue by drosengarten** [ZaxR/bulwark#57]
Currently, the library only checks a singular result output of a function.
By adding an optional extra parameter, a developer should be able to specify:
1. A singular return dataframe (default)
2. The name of an input variable into the function
3. An index of a result list/tuple that is a data frame.

This will allow developers to avoid making pass-through functions in order to use the library effectively.

for example:
for an input variable:
@bulwark.HasColumns(df='dataframe_1', columns='ColumnName1','ColumnName2'])
def my_function(dataframe_1)
    pass

For a singular output Dataframe:
@bulwark.HasColumns(columns='ColumnName1','ColumnName2'])
def my_function(dataframe_1)
    #create dataframe here
    df_result=.....
    return df_result
  
Or for an index of an output Dataframe
@bulwark.HasColumns(df=0, columns='ColumnName1', 'ColumnName2'])
@bulwark.HasColumns(df=1, columns='SecondColumnName1', 'SecondColumnName2'])
def my_function(dataframe_1)
    #create dataframe here
    df_result_1=.....
    df_result_2=.....
    return (df_result_1, df_result_2)

**Comment by ZaxR** [comment]
Thanks for the feedback. The current pattern to avoid a pass-through function would be to use the check version:

```
import bulwark.checks as ck

# for a variable
ck.has_columns(df=dataframe_1, columns=['ColumnName1', 'ColumnName2'])
# Alternatively, you can use pipe
```

Regarding the second two examples, I'm not quite sure what you mean. The second example is what the library currently does - the decorated function will check df_result. In the event that multiple dfs are fed through a function, the check(s) will be run for all of them. 

Do you have some real code examples you can share, so we can suss out what syntax upgrades might be useful? To my mind the cases that don't meet the existing capabilities of the library are more about code design philosophy.

**Comment by ZaxR** [comment]
Going to close since this there hasn't been any activity, but please feel free to add a fresh issue should you wish to follow up.
