### ISSUE TITLE
Drop Python 3.5?

### ISSUE THREAD

**Issue by jamesmyatt** [ZaxR/bulwark#68]
I was about to do a PR to add Python 3.8 to the build matrix, but I wondered about removing Python 3.5. The justification is that Pandas v1.0.0 requires Python 3.6.1 now. https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html

In particular, I wonder whether the policy going forwards should be to support the same Python as the latest stable Pandas release. What do you think?

**Comment by jamesmyatt** [comment]
Associated with this, it might be worth adding setting the minimum version of Pandas to match.

**Comment by ZaxR** [comment]
Yes re: the policy being supporting the same Pythons as the latest stable pandas release - that was always in my mind, but i guess I forgot to write it down.

**Comment by ZaxR** [comment]
Can you explain what you mean by minimum pandas version? I'm more cautious about that one.

**Comment by ZaxR** [comment]
And thanks in advance for the PR - I've been slammed with other open source projects the past couple months.

**Comment by hugovk** [comment]
See also NEP 29: "Recommend Python and Numpy version support as a community policy standard"

* https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by ZaxR** [comment]
@jamesmyatt and @hugovk - I took the minimum python and numpy/pandas support recommendations for the PR I just put out. If one of you has time, I'd appreciate a review.
