### ISSUE TITLE
Consider relicensing to LGPL

### ISSUE THREAD

**Issue by eganjs** [ZaxR/bulwark#71]
As a follow up to #58

The below is to the best of my understanding:

GPL is a blocker for me as I work for the UK Hydrographic Office, which is a UK government organisation.

Fortunately our policies allow for most licenses, with GPL being one of the few we cannot use.
That said, we can use LGPL, which provides almost all the same protections but does not require the libraries consumer to open source their code.

I would like to use this library but as said the GPL is a blocker for me, I kindly ask that the project considers relicensing based on the above.

**Comment by amcclosky** [comment]
I want to recommend this library instead of my company but GPL3 is basically a non-starter for including it in any of our major projects. Apache, MIT or LGPL would be more palatable for a lot of orgs I would imagine.

**Comment by ZaxR** [comment]
Based on this feedback, and issue #58 , I have changed the license to LGPL 3.0. Thanks for the feedback - hopefully now the license isn't a blocker :)

**Comment by amcclosky** [comment]
Thanks!
