### ISSUE TITLE
Could we have a report on the rows that are in error for `is_monotonic`?

### ISSUE THREAD

**Issue by ianozsvald** [ZaxR/bulwark#76]
Some of your excellent bulwark gives a report for row numbers that are in violation of a test but others don't (as for `is_monotonic` below). Might it make sense to add a report for rows that are in violation to help debug the data?

An expected output might indicate here that row 4 is in violation.

```
import bulwark.checks as ck
dfx = pd.DataFrame({'a': [1, 2, 3, 2]})
ck.is_monotonic(dfx[['a']], strict=True);

    277         if not good:
--> 278             raise AssertionError
    279 
    280     return df

AssertionError: 
```

**Comment by ZaxR** [comment]
Looking into this now. This will require a bit of a rewrite, because right now, unless strict=True, the function utilized the is_monotonic properties. In other words, if strict=False, the only check that happens is a single True/False for each column being monotonic or not. If we want to not only identify which columns are bad, but also which rows cause it, the code that determines monotonicity will need to change.

**Comment by ZaxR** [comment]
Something along the lines of the following should work. This example is just for increasing monotonicity:
```
from bulwark.generic import bad_locations
df = pd.DataFrame({'a': [1, 2, 3, 2, 3, 2], 'b': [5, 5, 4, 3, 4, 5]})

bad = ~(df['a'].diff().dropna() > 0)   # | (df['a'].diff().dropna() < 0)
bad_locations(pd.DataFrame(bad))
```
The only issue is that if you're checking for increasing or decreasing monotonicity, all rows should show as bad. What would you expect to see in that case? My thought is to just return a whole column name when all locations in a column are bad (generally for bad_locations, not just for this func)

**Comment by ZaxR** [comment]
Re: the above case where increasing=None, and a column isn't monotonic either increasing or decreasing, the rows that will be displayed as bad will be rows that are bad for either case in the PR to add this enhancement. Let me know if you'd expect different behavior, and we can change it.

**Comment by ZaxR** [comment]
This will be avail in v0.6.0

**Comment by ZaxR** [comment]
v0.6.1 is released, and a bug in the readthedocs building is resolved, so check-level docs are available online now. Here's the link to the upgraded is_monotonic docs: https://bulwark.readthedocs.io/en/latest/_source/bulwark.checks.html#bulwark.checks.is_monotonic

**Comment by ianozsvald** [comment]
Much obliged! I look forward to giving this a go, thanks. I plan to mention bulwark in some upcoming talks for "higher performance Pandas development", cheers
